pull_request_rules:
  - name: Automatic merge of scala-steward PRs 
    conditions:
      - head~=^update/
      - check-success=build-and-test
    actions:
      delete_head_branch: 
        force: true
      merge:
        method: merge
