pull_request_rules:
  - name: Automatic merge of scala-steward PRs 
    conditions:
      - head~=^update/
      - check-success=build-and-test
    actions:
      delete_head_branch: 
        force: true
      queue:
        method: rebase
        name: default
        
  - name: automatic merge of dependabot 🤖
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build-and-test
      - base=master
    actions:
      delete_head_branch: 
        force: true
      queue:
        method: rebase
        name: default

queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=build-and-test