addSbtPlugin("com.eed3si9n"              % "sbt-assembly"  % "1.2.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.2.2")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"   % "0.6.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo" % "0.11.0")
