addSbtPlugin("com.eed3si9n"              % "sbt-assembly"  % "0.15.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"  % "0.1.17")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"   % "0.5.3")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"  % "2.4.2")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo" % "0.10.0")
