name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run tests
        run: sbt test

      - name: Package artifact
        run: sbt assembly

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bus-stops-importer.jar
          path: modules/importer/target/scala-2.13/bus-stops-importer.jar
          if-no-files-found: error

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: build-and-test
    name: Docker Build, Tag, Push

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx # needed by docker/login-action@v1
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }} # token is on "github secrets"

      - name: Create Tag
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2.1.1
        with:
          images: ghcr.io/faustin0/bus-info/app # base name for tag
          tag-sha: true # using git short SHA

      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
