name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OPTIMIZE_NATIVE: ${{ github.ref == 'refs/heads/master' && 'true' || 'false' }}


jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'sbt'
          check-for-updates: true
          native-image-job-reports: true
          native-image-musl: true

      - name: Run tests
        run: sbt test

      - name: Package artifact
        run: sbt universal:packageBin

      - name: Package native artifact
        run: sbt 'show graalvm-native-image:packageBin'

      - name: Create API bootable zip
        run: zip -j api.zip modules/api/target/graalvm-native-image/api modules/api/src/main/resources/bootstrap

      - name: Upload importer artifact
        uses: actions/upload-artifact@v4
        with:
          name: bus-stops-importer.zip
          path: modules/importer/target/universal/importer-*.zip
          if-no-files-found: error

      - name: Upload API native artifact
        uses: actions/upload-artifact@v4
        with:
          name: native-api.zip
          path: api.zip
          if-no-files-found: error
